name: AI PR Reviewer
description: Review PR using OpenAI API
inputs:
  github-token:
    required: true
  openai-api-key:
    required: true
  assistant-id:
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
