name: PR Opened Bot

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  pr_commenter:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ReviewBotToken }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `**ReviewBot 🤖** says: Thanks @${context.payload.pull_request.user.login} for your PR! We'll review it soon.`
            });

      - name: Add labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ReviewBotToken }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['needs-review']
            });
